import { useEffect, useState } from "react";
import Sidebar from "../components/Sidebar";
import Navbar from "../components/Navbar";

export default function Appointments() {
  const [appointments, setAppointments] = useState([]); const [patient, setPatient] = useState(""); const [doctor, setDoctor] = useState(""); const [date, setDate] = useState(""); const [time, setTime] = useState(""); const [doctors, setDoctors] = useState([]);
  useEffect(() => { setAppointments(JSON.parse(localStorage.getItem("hospitalAppointments")) || []); setDoctors(JSON.parse(localStorage.getItem("doctors")) || []); }, []);
  const addAppointment = () => { if (!patient.trim() || !doctor.trim()) { alert("Please enter patient and doctor name"); return; } const updated = [...appointments, { id: Date.now(), patient: patient.trim(), doctor: doctor.trim(), date, time, status: "Confirmed" }]; setAppointments(updated); localStorage.setItem("hospitalAppointments", JSON.stringify(updated)); setPatient(""); setDoctor(""); setDate(""); setTime(""); };
  const removeAppointment = (id) => { const updated = appointments.filter((a) => a.id !== id); setAppointments(updated); localStorage.setItem("hospitalAppointments", JSON.stringify(updated)); };
  return <div className="app-shell"><Sidebar /><main className="main"><Navbar title="Appointments" />
    <section className="panel form-panel"><div className="panel-heading"><div><h3>Book appointment</h3><p>Create a new patient appointment.</p></div><span className="panel-badge green-badge">Simple scheduling</span></div><div className="form-grid"><div><label>Patient name</label><input value={patient} onChange={(e) => setPatient(e.target.value)} placeholder="Patient name" /></div><div><label>Doctor name</label><input list="doctor-options" value={doctor} onChange={(e) => setDoctor(e.target.value)} placeholder="Doctor name" /><datalist id="doctor-options">{doctors.map((d) => <option key={d.id} value={d.name} />)}</datalist></div><div><label>Date</label><input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></div><div><label>Time</label><input type="time" value={time} onChange={(e) => setTime(e.target.value)} /></div></div><div className="form-actions"><button className="primary-button" onClick={addAppointment}>Book appointment <span>→</span></button></div></section>
    <section className="panel"><div className="panel-heading"><div><h3>Upcoming appointments</h3><p>{appointments.length} appointment{appointments.length === 1 ? "" : "s"} in this browser</p></div></div>{appointments.length === 0 ? <div className="empty-state"><span>▣</span><h3>No appointments yet</h3><p>Use the form above to schedule one.</p></div> : <div className="appointment-list">{appointments.slice().reverse().map((a) => <div className="appointment-row" key={a.id}><div className="date-box"><strong>{a.date ? new Date(`${a.date}T00:00:00`).toLocaleDateString(undefined, { day: "2-digit" }) : "--"}</strong><span>{a.date ? new Date(`${a.date}T00:00:00`).toLocaleDateString(undefined, { month: "short" }) : "Date"}</span></div><div className="appointment-main"><strong>{a.patient}</strong><span>with {a.doctor}{a.time ? ` · ${a.time}` : ""}</span></div><span className="status">{a.status || "Confirmed"}</span><button className="delete-button" onClick={() => removeAppointment(a.id)} title="Delete appointment">×</button></div>)}</div>}</section>
  </main></div>;
}
